
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringJoiner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jabar
 */
// Authors : Rayan Jangda, Armand Daniel Sanchez, Eldrin Preston, Ismael Moreno, Jabari Fowler
public class admin_win extends javax.swing.JFrame {
    admin admin = new admin();
   
    int test4,test5,test6;
    String course_nm;
    private Object[][] data;
    private TableRowSorter<TableModel> rowSorter; 
    /**
     * Creates new form admin_win
     */
    
    public admin_win() {
        initComponents();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_student = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        save_button = new javax.swing.JButton();
        Load_button = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        course_table = new javax.swing.JTable();
        delete_student = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        phone_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        addy_field = new javax.swing.JTextField();
        city_field = new javax.swing.JTextField();
        state_field = new javax.swing.JTextField();
        malefemale_field = new javax.swing.JTextField();
        major_field = new javax.swing.JTextField();
        add_course = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        admin_name_display = new javax.swing.JLabel();
        add_course_student = new javax.swing.JButton();
        see_course_student = new javax.swing.JButton();
        save_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_student.setText("Add Student");
        Add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_studentActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "ID", "Campus", "Class", "Address", "Phone Number", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        Load_button.setText("Load");
        Load_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_buttonActionPerformed(evt);
            }
        });

        search_field.setText("Search Students");
        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });

        course_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course #", "Instructor", "Type", "Campus"
            }
        ));
        jScrollPane2.setViewportView(course_table);

        delete_student.setText("Delete Student");
        delete_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_studentActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Phone Number:");

        jLabel3.setText("Address:");

        jLabel4.setText("M/F");

        jLabel5.setText("Major");

        jLabel6.setText("City");

        jLabel7.setText("State");

        jLabel8.setText("Email");

        name_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        phone_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        email_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addy_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        city_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        state_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        malefemale_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        major_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        add_course.setText("Add Course");
        add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_courseActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Welcome");

        admin_name_display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin_name_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_name_display.setText("jLabel10");

        add_course_student.setText("Add Student Course");
        add_course_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_course_studentActionPerformed(evt);
            }
        });

        see_course_student.setText("See Student Courses");
        see_course_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see_course_studentActionPerformed(evt);
            }
        });

        save_button1.setText("LogOut");
        save_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(admin_name_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addy_field, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_field, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malefemale_field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(major_field)
                            .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_course, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add_student)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_student)
                        .addGap(193, 193, 193)
                        .addComponent(add_course_student)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(see_course_student)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button1)
                        .addGap(142, 142, 142)
                        .addComponent(save_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Load_button)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_course, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(name_field))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone_field))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email_field)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(admin_name_display, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addy_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malefemale_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(major_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_student)
                    .addComponent(save_button)
                    .addComponent(Load_button)
                    .addComponent(delete_student)
                    .addComponent(add_course_student)
                    .addComponent(see_course_student)
                    .addComponent(save_button1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_studentActionPerformed
        String fName = JOptionPane.showInputDialog(null, "Enter first name: ");
        String lName = JOptionPane.showInputDialog(null, "Enter last name: ");
        int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter ID: "));
        String campus = JOptionPane.showInputDialog(null, "Enter Campus: ");
        String class_r = JOptionPane.showInputDialog(null, "Enter Class: ");
        int num_of_classes = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter the Number of Classes: "));
        
        
        boolean found = false;
        if(found == false){
       student e = new student(fName,lName,id);
         for(int i = 0; i < num_of_classes; i++){
                ArrayList<Object> tempCourse = new ArrayList<>();
                
                String courseName = JOptionPane.showInputDialog(null, "Course " + (i + 1) + " Name: ");
                int test1 = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter test 1: "));
                int test2 = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter test 2: "));
                int test3 = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter test 3: "));
                
                tempCourse.add(courseName);
                tempCourse.add(test1);
                tempCourse.add(test2);
                tempCourse.add(test3);
                
                e.courses.add(tempCourse);               
            }    
            
            e.calcGradeLetter();
            e.calcGPA();
            admin.students.add(e);
        }
            
            String [] Headers = new String [] {
                "First Name", "Last Name", "ID", "Campus", "Class", "Address", "Phone Number", "Email"
            };
        
        
        DefaultTableModel model = new DefaultTableModel(data,Headers);
        
        
        Object[] add = new Object[5];
        
        add[0] = fName;
        add[1] = lName;
        add[2] = id;
        add[3] = campus;
        add[4] = class_r;
        
       
        
        
          ((DefaultTableModel) jTable1.getModel()).addRow(add);
        
        
    }//GEN-LAST:event_Add_studentActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String filePath = "txtfile.txt";
        File file = new File(filePath);
        try {
            StringJoiner joiner = new StringJoiner(",");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
//            for(int i = 0; i< jTable1.getColumnCount();i++){
//                joiner.add(jTable1.getColumnName(i));
//            }
//            System.out.println(joiner.toString());
//            bw.write(joiner.toString());
//            bw.newLine();
//           
            for(int i = 0; i < jTable1.getRowCount(); i++){//rows
                joiner = new StringJoiner(",");
                for(int j = 0; j < jTable1.getColumnCount(); j++){//columns
                    Object obj = jTable1.getValueAt(i,j);
                    String value = obj == null ? "null" : obj.toString();
                    joiner.add(value);
                }
                System.out.println(joiner.toString());
                bw.write(joiner.toString());
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
           ex.notifyAll();
        }// TODO add your handling code here:
        // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_save_buttonActionPerformed

    private void Load_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_buttonActionPerformed
          
        String filePath = "txtfile.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                
                String[] row = lines[i].toString().split(",");
                if(row != null){
                    model.addRow(row);
                }
            }
            
        } catch (FileNotFoundException ex) {
           ex.printStackTrace();
        }
        
        filePath = "class list.txt";
        file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            DefaultTableModel model = (DefaultTableModel)course_table.getModel();
            
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                
                String[] row = lines[i].toString().split(",");
                if(row != null){
                    model.addRow(row);
                }
            }
            
        } catch (FileNotFoundException ex) {
           ex.printStackTrace();
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_Load_buttonActionPerformed

    private void delete_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_studentActionPerformed
       
        
        while(jTable1.getRowCount() > 0){
          ((DefaultTableModel) jTable1.getModel()).removeRow(jTable1.getSelectedRow());
          
        }// TODO add your handling code here:
    }//GEN-LAST:event_delete_studentActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
       String search = search_field.getText();
       rowSorter  = new TableRowSorter<>(jTable1.getModel());
       jTable1.setRowSorter(rowSorter);
       if(search.trim().length() == 0){
           rowSorter.setRowFilter(null);
       }else{
           rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + search));
       }
// TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row_in = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        name_field.setText(model.getValueAt(row_in,0).toString()+","+ model.getValueAt(row_in, 1).toString());
        phone_field.setText(model.getValueAt(row_in, 6).toString());
        email_field.setText(model.getValueAt(row_in, 7).toString());
        addy_field.setText(model.getValueAt(row_in, 5).toString());
        state_field.setText("Texas");
        city_field.setText("Houston");
        malefemale_field.setText("M");
        major_field.setText("B.S. - Computer Science");
        
              
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void add_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_courseActionPerformed
             
        
        Object[] add = new Object[4];
        
        add[0] = JOptionPane.showInputDialog(null, "Enter Course ID: ");
        add[1] = JOptionPane.showInputDialog(null, "Instructor: ");
        add[2] = JOptionPane.showInputDialog(null, "Instruction Mode: ");
        add[3] = JOptionPane.showInputDialog(null, "Campus: ");
        
        
       ((DefaultTableModel) course_table.getModel()).addRow(add);
        
 // TODO add your handling code here:
    }//GEN-LAST:event_add_courseActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void add_course_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_course_studentActionPerformed
        String fName = JOptionPane.showInputDialog(null, "Which Student would you like to add a course too?: ");
        String filePath = fName + " info" + ".txt";
        File file = new File(filePath);
        String course_add = JOptionPane.showInputDialog(null,"Which Course would you like to add?");
        String instruct_add = JOptionPane.showInputDialog(null,"Which Instructor?");
        String time_add = JOptionPane.showInputDialog(null,"What Time?");
        String grade_add = JOptionPane.showInputDialog(null,"Do You Have any grades?");
        try {
            StringJoiner joiner = new StringJoiner(",");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
//            for(int i = 0; i< jTable1.getColumnCount();i++){
//                joiner.add(jTable1.getColumnName(i));
//            }
//            System.out.println(joiner.toString());
//            bw.write(joiner.toString());
//            bw.newLine();
//           
            for(int i = 0; i < 1; i++){//rows
                joiner = new StringJoiner(",");
                for(int j = 0; j < 1; j++){//columns
                    
                    String value = course_add+","+instruct_add+","+time_add+","+grade_add;
                    joiner.add(value);
                }
                System.out.println(joiner.toString());
                bw.write(joiner.toString());
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
           ex.notifyAll();
        }// TODO add your handling code here:
    }//GEN-LAST:event_add_course_studentActionPerformed

    private void see_course_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see_course_studentActionPerformed
        
        String name = JOptionPane.showInputDialog(null, "Which Student would you like to see courses for? ");
        
        display_grades sam = new display_grades();
        sam.jLabel1.setText(name);
        sam.loadFile(name);
        sam.displayGrades(name);
        sam.displayGPA(name);
        sam.setVisible(true);
        sam.pack();
        sam.setLocationRelativeTo(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_see_course_studentActionPerformed

    private void save_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_button1ActionPerformed
        login w = new login();
        w.setVisible(true);
        setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_save_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_win().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_student;
    private javax.swing.JButton Load_button;
    private javax.swing.JButton add_course;
    private javax.swing.JButton add_course_student;
    private javax.swing.JTextField addy_field;
    public javax.swing.JLabel admin_name_display;
    private javax.swing.JTextField city_field;
    private javax.swing.JTable course_table;
    private javax.swing.JButton delete_student;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField major_field;
    private javax.swing.JTextField malefemale_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField phone_field;
    private javax.swing.JButton save_button;
    private javax.swing.JButton save_button1;
    private javax.swing.JTextField search_field;
    private javax.swing.JButton see_course_student;
    private javax.swing.JTextField state_field;
    // End of variables declaration//GEN-END:variables
}
